"""Unified high-level façade for Dobot V4 robots.

All public dashboard commands are forwarded as one-liner methods directly on
:class:`DobotRobot`, providing full IDE autocompletion and static type
checking.  The forwarding region is auto-generated — to regenerate it after
the dashboard API changes, run::

    python -m dobot_api_v4._codegen

Methods that compose multiple sub-objects (lifecycle, error convenience,
feedback convenience) are defined directly on this class."""

import collections.abc
from typing import Optional, Union

import numpy as np

from .commands.dashboard import DobotApiDashboard
from .dtypes import FeedbackData, Pose
from .error_monitor import RobotErrorMonitor
from .feedback import DobotApiFeedback


class DobotRobot:
    """Unified high-level robot interface.

    Eagerly creates the dashboard (port 29999) and error monitor (HTTP 22000).
    Feedback connections (30004, 30005, 30006) are created lazily on first
    access.

    All public dashboard commands are forwarded as auto-generated one-liner
    methods.  Run ``python -m dobot_api_v4._codegen`` to regenerate the
    forwarding region when the dashboard API changes.

    Example::

        with DobotRobot("192.168.1.6") as robot:
            robot.enable_robot()
            pose = robot.get_pose()       # returns Pose
            qid  = robot.mov_j(...)       # returns int
            data = robot.feedback_data()  # returns FeedbackData | None
    """

    def __init__(self, ip: str, *, language: str = "en") -> None:
        """Initialize robot connections.

        Args:
            ip: Robot IP address.
            language: Default language for error messages.
        """
        self.ip = ip
        self.dashboard = DobotApiDashboard(ip, 29999)
        self.errors = RobotErrorMonitor(ip)
        self._language = language
        self._feedback: Optional[DobotApiFeedback] = None
        self._feedback_30005: Optional[DobotApiFeedback] = None
        self._feedback_30006: Optional[DobotApiFeedback] = None

    # --- BEGIN GENERATED FORWARDS ---
    # Auto-generated by `python -m dobot_api_v4._codegen` — do not edit manually.
    from collections.abc import Sequence
    from typing import Optional

    # --- System ---

    def enable_robot(
        self,
        load: float = 0.0,
        center_x: float = 0.0,
        center_y: float = 0.0,
        center_z: float = 0.0,
        is_check: int = -1,
    ) -> None:
        return self.dashboard.enable_robot(load, center_x, center_y, center_z, is_check)

    def disable_robot(self) -> None:
        return self.dashboard.disable_robot()

    def clear_error(self) -> None:
        return self.dashboard.clear_error()

    def power_on(self) -> None:
        return self.dashboard.power_on()

    def run_script(self, project_name: str) -> None:
        return self.dashboard.run_script(project_name)

    def stop_script(self) -> None:
        return self.dashboard.stop_script()

    def pause_script(self) -> None:
        return self.dashboard.pause_script()

    def resume(self) -> None:
        return self.dashboard.resume()

    def emergency_stop(self, mode: int) -> None:
        return self.dashboard.emergency_stop(mode)

    def brake_control(self, axis_id: int, value: int) -> None:
        return self.dashboard.brake_control(axis_id, value)

    def request_control(self) -> None:
        return self.dashboard.request_control()

    def reset_robot(self) -> None:
        return self.dashboard.reset_robot()

    def tcp_send_and_parse(self, cmd: str) -> str:
        return self.dashboard.tcp_send_and_parse(cmd)

    def sleep(self, count: int) -> None:
        return self.dashboard.sleep(count)

    # --- Config ---

    def speed_factor(self, speed: int) -> None:
        return self.dashboard.speed_factor(speed)

    def acc_j(self, speed: int) -> None:
        return self.dashboard.acc_j(speed)

    def acc_l(self, speed: int) -> None:
        return self.dashboard.acc_l(speed)

    def vel_j(self, speed: int) -> None:
        return self.dashboard.vel_j(speed)

    def vel_l(self, speed: int) -> None:
        return self.dashboard.vel_l(speed)

    def cp(self, ratio: int) -> None:
        return self.dashboard.cp(ratio)

    def user(self, index: int) -> None:
        return self.dashboard.user(index)

    def set_user(self, index: int, table: str) -> None:
        return self.dashboard.set_user(index, table)

    def calc_user(self, index: int, matrix_direction: int, table: str) -> None:
        return self.dashboard.calc_user(index, matrix_direction, table)

    def tool(self, index: int) -> None:
        return self.dashboard.tool(index)

    def set_tool(self, index: int, table: str) -> None:
        return self.dashboard.set_tool(index, table)

    def calc_tool(self, index: int, matrix_direction: int, table: str) -> None:
        return self.dashboard.calc_tool(index, matrix_direction, table)

    def set_payload(
        self,
        load: float = 0.0,
        x: float = 0.0,
        y: float = 0.0,
        z: float = 0.0,
        name: str = "F",
    ) -> None:
        return self.dashboard.set_payload(load, x, y, z, name)

    def set_collision_level(self, level: int) -> None:
        return self.dashboard.set_collision_level(level)

    def set_back_distance(self, distance: int) -> None:
        return self.dashboard.set_back_distance(distance)

    def set_post_collision_mode(self, mode: int) -> None:
        return self.dashboard.set_post_collision_mode(mode)

    def drag_sensitivity(self, index: int, value: int) -> None:
        return self.dashboard.drag_sensitivity(index, value)

    def enable_safe_skin(self, status: int) -> None:
        return self.dashboard.enable_safe_skin(status)

    def set_safe_skin(self, part: int, status: int) -> None:
        return self.dashboard.set_safe_skin(part, status)

    def set_safe_wall_enable(self, index: int, value: int) -> None:
        return self.dashboard.set_safe_wall_enable(index, value)

    def set_work_zone_enable(self, index: int, value: int) -> None:
        return self.dashboard.set_work_zone_enable(index, value)

    def offset_para(
        self, x: float, y: float, z: float, rx: float, ry: float, rz: float
    ) -> None:
        return self.dashboard.offset_para(x, y, z, rx, ry, rz)

    def set_resume_offset(self, distance: float) -> None:
        return self.dashboard.set_resume_offset(distance)

    def start_rt_offset(self) -> None:
        return self.dashboard.start_rt_offset()

    def end_rt_offset(self) -> None:
        return self.dashboard.end_rt_offset()

    # --- I/O ---

    def do_output(self, index: int, status: int, time: int = -1) -> None:
        return self.dashboard.do_output(index, status, time)

    def do_instant(self, index: int, status: int) -> None:
        return self.dashboard.do_instant(index, status)

    def get_do(self, index: int) -> int:
        return self.dashboard.get_do(index)

    def do_group(self, *index_value: int) -> None:
        return self.dashboard.do_group(*index_value)

    def get_do_group(self, *index_value: int) -> str:
        return self.dashboard.get_do_group(*index_value)

    def do_group_dec(self, group: int, value: int) -> None:
        return self.dashboard.do_group_dec(group, value)

    def get_do_group_dec(self, group: int, value: int) -> str:
        return self.dashboard.get_do_group_dec(group, value)

    def tool_do(self, index: int, status: int) -> None:
        return self.dashboard.tool_do(index, status)

    def tool_do_instant(self, index: int, status: int) -> None:
        return self.dashboard.tool_do_instant(index, status)

    def get_tool_do(self, index: int) -> int:
        return self.dashboard.get_tool_do(index)

    def ao(self, index: int, value: float) -> None:
        return self.dashboard.ao(index, value)

    def ao_instant(self, index: int, value: float) -> None:
        return self.dashboard.ao_instant(index, value)

    def get_ao(self, index: int) -> str:
        return self.dashboard.get_ao(index)

    def di(self, index: int) -> int:
        return self.dashboard.di(index)

    def di_group(self, *index_value: int) -> str:
        return self.dashboard.di_group(*index_value)

    def di_group_dec(self, group: int, value: int) -> str:
        return self.dashboard.di_group_dec(group, value)

    def tool_di(self, index: int) -> int:
        return self.dashboard.tool_di(index)

    def ai(self, index: int) -> int:
        return self.dashboard.ai(index)

    def tool_ai(self, index: int) -> int:
        return self.dashboard.tool_ai(index)

    def set_tool_485(
        self, baud: int, parity: str = "", stopbit: int = -1, identify: int = -1
    ) -> None:
        return self.dashboard.set_tool_485(baud, parity, stopbit, identify)

    def set_tool_power(self, status: int, identify: int = -1) -> None:
        return self.dashboard.set_tool_power(status, identify)

    def set_tool_mode(self, mode: int, port_type: int, identify: int = -1) -> None:
        return self.dashboard.set_tool_mode(mode, port_type, identify)

    # --- Modbus ---

    def modbus_create(self, ip: str, port: int, slave_id: int, is_rtu: int = -1) -> int:
        return self.dashboard.modbus_create(ip, port, slave_id, is_rtu)

    def modbus_rtu_create(
        self,
        slave_id: int,
        baud: int,
        parity: str = "",
        data_bit: int = 8,
        stop_bit: int = -1,
    ) -> int:
        return self.dashboard.modbus_rtu_create(
            slave_id, baud, parity, data_bit, stop_bit
        )

    def modbus_close(self, index: int) -> None:
        return self.dashboard.modbus_close(index)

    def get_in_bits(self, index: int, addr: int, count: int) -> str:
        return self.dashboard.get_in_bits(index, addr, count)

    def get_in_regs(self, index: int, addr: int, count: int, val_type: str = "") -> str:
        return self.dashboard.get_in_regs(index, addr, count, val_type)

    def get_coils(self, index: int, addr: int, count: int) -> str:
        return self.dashboard.get_coils(index, addr, count)

    def set_coils(self, index: int, addr: int, count: int, val_tab: str) -> None:
        return self.dashboard.set_coils(index, addr, count, val_tab)

    def get_hold_regs(
        self, index: int, addr: int, count: int, val_type: str = ""
    ) -> str:
        return self.dashboard.get_hold_regs(index, addr, count, val_type)

    def set_hold_regs(
        self, index: int, addr: int, count: int, val_tab: str, val_type: str = ""
    ) -> None:
        return self.dashboard.set_hold_regs(index, addr, count, val_tab, val_type)

    def get_input_bool(self, address: int) -> int:
        return self.dashboard.get_input_bool(address)

    def get_input_int(self, address: int) -> int:
        return self.dashboard.get_input_int(address)

    def get_input_float(self, address: int) -> str:
        return self.dashboard.get_input_float(address)

    def get_output_bool(self, address: int) -> int:
        return self.dashboard.get_output_bool(address)

    def get_output_int(self, address: int) -> int:
        return self.dashboard.get_output_int(address)

    def get_output_float(self, address: int) -> str:
        return self.dashboard.get_output_float(address)

    def set_output_bool(self, address: int, value: int) -> None:
        return self.dashboard.set_output_bool(address, value)

    def set_output_int(self, address: int, value: int) -> None:
        return self.dashboard.set_output_int(address, value)

    def set_output_float(self, address: int, value: float) -> None:
        return self.dashboard.set_output_float(address, value)

    # --- Query ---

    def robot_mode(self) -> int:
        return self.dashboard.robot_mode()

    def get_angle(self) -> Pose:
        return self.dashboard.get_angle()

    def get_pose(self, user: int = -1, tool: int = -1) -> Pose:
        return self.dashboard.get_pose(user, tool)

    def get_error_id(self) -> tuple[int, ...]:
        return self.dashboard.get_error_id()

    def positive_kin(
        self,
        j1: float,
        j2: float,
        j3: float,
        j4: float,
        j5: float,
        j6: float,
        user: int = -1,
        tool: int = -1,
    ) -> Pose:
        return self.dashboard.positive_kin(j1, j2, j3, j4, j5, j6, user, tool)

    def inverse_kin(
        self,
        x: float,
        y: float,
        z: float,
        rx: float,
        ry: float,
        rz: float,
        user: int = -1,
        tool: int = -1,
        use_joint_near: int = -1,
        joint_near: str = "",
    ) -> Pose:
        return self.dashboard.inverse_kin(
            x, y, z, rx, ry, rz, user, tool, use_joint_near, joint_near
        )

    def inverse_solution(
        self,
        x: float,
        y: float,
        z: float,
        rx: float,
        ry: float,
        rz: float,
        user: int = -1,
        tool: int = -1,
        is_joint: int = 0,
    ) -> Pose:
        return self.dashboard.inverse_solution(
            x, y, z, rx, ry, rz, user, tool, is_joint
        )

    def get_current_command_id(self) -> int:
        return self.dashboard.get_current_command_id()

    def path_recovery(self) -> None:
        return self.dashboard.path_recovery()

    def path_recovery_stop(self) -> None:
        return self.dashboard.path_recovery_stop()

    def path_recovery_status(self) -> int:
        return self.dashboard.path_recovery_status()

    def log_export_usb(self, range: int) -> None:
        return self.dashboard.log_export_usb(range)

    def get_export_status(self) -> int:
        return self.dashboard.get_export_status()

    def start_drag(self) -> None:
        return self.dashboard.start_drag()

    def stop_drag(self) -> None:
        return self.dashboard.stop_drag()

    def create_tray(self, *args: object, **kwargs: object) -> None:
        return self.dashboard.create_tray(*args, **kwargs)

    def get_tray_point(self, *args: object, **kwargs: object) -> Pose:
        return self.dashboard.get_tray_point(*args, **kwargs)

    # --- Motion ---

    def mov_j(
        self,
        a1: float,
        b1: float,
        c1: float,
        d1: float,
        e1: float,
        f1: float,
        coordinate_mode: int,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
    ) -> int:
        return self.dashboard.mov_j(
            a1, b1, c1, d1, e1, f1, coordinate_mode, user, tool, a, v, cp
        )

    def mov_l(
        self,
        a1: float,
        b1: float,
        c1: float,
        d1: float,
        e1: float,
        f1: float,
        coordinate_mode: int,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        speed: int = -1,
        cp: int = -1,
        r: int = -1,
    ) -> int:
        return self.dashboard.mov_l(
            a1, b1, c1, d1, e1, f1, coordinate_mode, user, tool, a, v, speed, cp, r
        )

    def servo_j(
        self,
        j1: float,
        j2: float,
        j3: float,
        j4: float,
        j5: float,
        j6: float,
        t: float = -1.0,
        ahead_time: float = -1.0,
        gain: float = -1.0,
    ) -> int:
        return self.dashboard.servo_j(j1, j2, j3, j4, j5, j6, t, ahead_time, gain)

    def servo_p(
        self,
        x: float,
        y: float,
        z: float,
        rx: float,
        ry: float,
        rz: float,
        t: float = -1.0,
        ahead_time: float = -1.0,
        gain: float = -1.0,
    ) -> int:
        return self.dashboard.servo_p(x, y, z, rx, ry, rz, t, ahead_time, gain)

    def mov_l_io(
        self,
        a1: float,
        b1: float,
        c1: float,
        d1: float,
        e1: float,
        f1: float,
        coordinate_mode: int,
        mode: int,
        distance: int,
        index: int,
        status: int,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        speed: int = -1,
        cp: int = -1,
        r: int = -1,
    ) -> int:
        return self.dashboard.mov_l_io(
            a1,
            b1,
            c1,
            d1,
            e1,
            f1,
            coordinate_mode,
            mode,
            distance,
            index,
            status,
            user,
            tool,
            a,
            v,
            speed,
            cp,
            r,
        )

    def mov_j_io(
        self,
        a1: float,
        b1: float,
        c1: float,
        d1: float,
        e1: float,
        f1: float,
        coordinate_mode: int,
        mode: int,
        distance: int,
        index: int,
        status: int,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
    ) -> int:
        return self.dashboard.mov_j_io(
            a1,
            b1,
            c1,
            d1,
            e1,
            f1,
            coordinate_mode,
            mode,
            distance,
            index,
            status,
            user,
            tool,
            a,
            v,
            cp,
        )

    def arc(
        self,
        a1: float,
        b1: float,
        c1: float,
        d1: float,
        e1: float,
        f1: float,
        a2: float,
        b2: float,
        c2: float,
        d2: float,
        e2: float,
        f2: float,
        coordinate_mode: int,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        speed: int = -1,
        cp: int = -1,
        r: int = -1,
    ) -> int:
        return self.dashboard.arc(
            a1,
            b1,
            c1,
            d1,
            e1,
            f1,
            a2,
            b2,
            c2,
            d2,
            e2,
            f2,
            coordinate_mode,
            user,
            tool,
            a,
            v,
            speed,
            cp,
            r,
        )

    def circle(
        self,
        a1: float,
        b1: float,
        c1: float,
        d1: float,
        e1: float,
        f1: float,
        a2: float,
        b2: float,
        c2: float,
        d2: float,
        e2: float,
        f2: float,
        coordinate_mode: int,
        count: int,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        speed: int = -1,
        cp: int = -1,
        r: int = -1,
    ) -> int:
        return self.dashboard.circle(
            a1,
            b1,
            c1,
            d1,
            e1,
            f1,
            a2,
            b2,
            c2,
            d2,
            e2,
            f2,
            coordinate_mode,
            count,
            user,
            tool,
            a,
            v,
            speed,
            cp,
            r,
        )

    def arc_io(
        self,
        a1: float,
        b1: float,
        c1: float,
        d1: float,
        e1: float,
        f1: float,
        a2: float,
        b2: float,
        c2: float,
        d2: float,
        e2: float,
        f2: float,
        coordinate_mode: int,
        *io_params: Union[list, tuple],
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        speed: int = -1,
        cp: int = -1,
        r: int = -1,
        mode: int = -1,
    ) -> int:
        return self.dashboard.arc_io(
            a1,
            b1,
            c1,
            d1,
            e1,
            f1,
            a2,
            b2,
            c2,
            d2,
            e2,
            f2,
            coordinate_mode,
            *io_params,
            user=user,
            tool=tool,
            a=a,
            v=v,
            speed=speed,
            cp=cp,
            r=r,
            mode=mode,
        )

    def move_jog(
        self, axis_id: str = "", coord_type: int = -1, user: int = -1, tool: int = -1
    ) -> None:
        return self.dashboard.move_jog(axis_id, coord_type, user, tool)

    def get_start_pose(self, trace_name: str) -> Pose:
        return self.dashboard.get_start_pose(trace_name)

    def start_path(
        self,
        trace_name: str,
        is_const: int = -1,
        multi: float = -1.0,
        user: int = -1,
        tool: int = -1,
    ) -> int:
        return self.dashboard.start_path(trace_name, is_const, multi, user, tool)

    def rel_mov_j_tool(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
    ) -> int:
        return self.dashboard.rel_mov_j_tool(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            user,
            tool,
            a,
            v,
            cp,
        )

    def rel_mov_l_tool(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        speed: int = -1,
        cp: int = -1,
        r: int = -1,
    ) -> int:
        return self.dashboard.rel_mov_l_tool(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            user,
            tool,
            a,
            v,
            speed,
            cp,
            r,
        )

    def rel_mov_j_user(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
    ) -> int:
        return self.dashboard.rel_mov_j_user(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            user,
            tool,
            a,
            v,
            cp,
        )

    def rel_mov_l_user(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        speed: int = -1,
        cp: int = -1,
        r: int = -1,
    ) -> int:
        return self.dashboard.rel_mov_l_user(
            offset_x,
            offset_y,
            offset_z,
            offset_rx,
            offset_ry,
            offset_rz,
            user,
            tool,
            a,
            v,
            speed,
            cp,
            r,
        )

    def rel_joint_mov_j(
        self,
        offset1: float,
        offset2: float,
        offset3: float,
        offset4: float,
        offset5: float,
        offset6: float,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
    ) -> int:
        return self.dashboard.rel_joint_mov_j(
            offset1, offset2, offset3, offset4, offset5, offset6, a, v, cp
        )

    def rel_point_tool(
        self,
        coordinate_mode: int,
        a1: float,
        b1: float,
        c1: float,
        d1: float,
        e1: float,
        f1: float,
        x: float,
        y: float,
        z: float,
        rx: float,
        ry: float,
        rz: float,
    ) -> int:
        return self.dashboard.rel_point_tool(
            coordinate_mode, a1, b1, c1, d1, e1, f1, x, y, z, rx, ry, rz
        )

    def rel_point_user(
        self,
        coordinate_mode: int,
        a1: float,
        b1: float,
        c1: float,
        d1: float,
        e1: float,
        f1: float,
        x: float,
        y: float,
        z: float,
        rx: float,
        ry: float,
        rz: float,
    ) -> int:
        return self.dashboard.rel_point_user(
            coordinate_mode, a1, b1, c1, d1, e1, f1, x, y, z, rx, ry, rz
        )

    def rel_joint(
        self,
        j1: float,
        j2: float,
        j3: float,
        j4: float,
        j5: float,
        j6: float,
        offset1: float,
        offset2: float,
        offset3: float,
        offset4: float,
        offset5: float,
        offset6: float,
    ) -> int:
        return self.dashboard.rel_joint(
            j1, j2, j3, j4, j5, j6, offset1, offset2, offset3, offset4, offset5, offset6
        )

    def move_l(
        self,
        a1: float,
        b1: float,
        c1: float,
        d1: float,
        e1: float,
        f1: float,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        speed: int = -1,
        cp: int = -1,
        r: int = -1,
    ) -> int:
        return self.dashboard.move_l(
            a1, b1, c1, d1, e1, f1, user, tool, a, v, speed, cp, r
        )

    def mov_s(
        self,
        file: Optional[str] = None,
        coordinate_mode: int = -1,
        points: Optional[
            collections.abc.Sequence[collections.abc.Sequence[float]]
        ] = None,
        user: int = -1,
        tool: int = -1,
        v: int = -1,
        speed: int = -1,
        a: int = -1,
        freq: int = -1,
    ) -> int:
        return self.dashboard.mov_s(
            file, coordinate_mode, points, user, tool, v, speed, a, freq
        )

    def run_to(
        self,
        a1: float,
        b1: float,
        c1: float,
        d1: float,
        e1: float,
        f1: float,
        move_type: int,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
    ) -> None:
        return self.dashboard.run_to(
            a1, b1, c1, d1, e1, f1, move_type, user, tool, a, v
        )

    # --- Force ---

    def enable_ft_sensor(self, status: int) -> None:
        return self.dashboard.enable_ft_sensor(status)

    def six_force_home(self) -> None:
        return self.dashboard.six_force_home()

    def get_force(self, tool: int = -1) -> Pose:
        return self.dashboard.get_force(tool)

    def force_drive_mode(
        self, x: int, y: int, z: int, rx: int, ry: int, rz: int, user: int = -1
    ) -> None:
        return self.dashboard.force_drive_mode(x, y, z, rx, ry, rz, user)

    def force_drive_speed(self, speed: int) -> None:
        return self.dashboard.force_drive_speed(speed)

    def fc_force_mode(
        self,
        x: int,
        y: int,
        z: int,
        rx: int,
        ry: int,
        rz: int,
        fx: int,
        fy: int,
        fz: int,
        frx: int,
        fry: int,
        frz: int,
        reference: int = -1,
        user: int = -1,
        tool: int = -1,
    ) -> None:
        return self.dashboard.fc_force_mode(
            x, y, z, rx, ry, rz, fx, fy, fz, frx, fry, frz, reference, user, tool
        )

    def fc_set_deviation(
        self, x: int, y: int, z: int, rx: int, ry: int, rz: int, control_type: int = -1
    ) -> None:
        return self.dashboard.fc_set_deviation(x, y, z, rx, ry, rz, control_type)

    def fc_set_force_limit(
        self, x: int, y: int, z: int, rx: int, ry: int, rz: int
    ) -> None:
        return self.dashboard.fc_set_force_limit(x, y, z, rx, ry, rz)

    def fc_set_mass(self, x: int, y: int, z: int, rx: int, ry: int, rz: int) -> None:
        return self.dashboard.fc_set_mass(x, y, z, rx, ry, rz)

    def fc_set_stiffness(
        self, x: int, y: int, z: int, rx: int, ry: int, rz: int
    ) -> None:
        return self.dashboard.fc_set_stiffness(x, y, z, rx, ry, rz)

    def fc_set_damping(self, x: int, y: int, z: int, rx: int, ry: int, rz: int) -> None:
        return self.dashboard.fc_set_damping(x, y, z, rx, ry, rz)

    def fc_off(self) -> None:
        return self.dashboard.fc_off()

    def fc_set_force_speed_limit(
        self, x: int, y: int, z: int, rx: int, ry: int, rz: int
    ) -> None:
        return self.dashboard.fc_set_force_speed_limit(x, y, z, rx, ry, rz)

    def fc_set_force(self, x: int, y: int, z: int, rx: int, ry: int, rz: int) -> None:
        return self.dashboard.fc_set_force(x, y, z, rx, ry, rz)

    def fc_collision_switch(self, enable: int) -> None:
        return self.dashboard.fc_collision_switch(enable)

    def set_fc_collision(self, force: float, torque: float) -> None:
        return self.dashboard.set_fc_collision(force, torque)

    # --- Conveyor ---

    def cnv_init(self, index: int) -> None:
        return self.dashboard.cnv_init(index)

    def cnv_mov_l(
        self,
        j1: float,
        j2: float,
        j3: float,
        j4: float,
        j5: float,
        j6: float,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
        r: int = -1,
    ) -> int:
        return self.dashboard.cnv_mov_l(j1, j2, j3, j4, j5, j6, user, tool, a, v, cp, r)

    def cnv_mov_c(
        self,
        j1a: float,
        j2a: float,
        j3a: float,
        j4a: float,
        j5a: float,
        j6a: float,
        j1b: float,
        j2b: float,
        j3b: float,
        j4b: float,
        j5b: float,
        j6b: float,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
        r: int = -1,
        mode: int = 1,
    ) -> int:
        return self.dashboard.cnv_mov_c(
            j1a,
            j2a,
            j3a,
            j4a,
            j5a,
            j6a,
            j1b,
            j2b,
            j3b,
            j4b,
            j5b,
            j6b,
            user,
            tool,
            a,
            v,
            cp,
            r,
            mode,
        )

    def get_cnv_object(self, obj_id: int) -> str:
        return self.dashboard.get_cnv_object(obj_id)

    def set_cnv_point_offset(self, x_offset: float, y_offset: float) -> None:
        return self.dashboard.set_cnv_point_offset(x_offset, y_offset)

    def set_cnv_time_compensation(self, time: int) -> None:
        return self.dashboard.set_cnv_time_compensation(time)

    def start_sync_cnv(self) -> None:
        return self.dashboard.start_sync_cnv()

    def stop_sync_cnv(self) -> None:
        return self.dashboard.stop_sync_cnv()

    # --- Weld ---

    def arc_track_start(self) -> None:
        return self.dashboard.arc_track_start()

    def arc_track_params(
        self,
        sample_time: int,
        coordinate_type: int,
        up_down_compensation_min: float,
        up_down_compensation_max: float,
        up_down_compensation_offset: float,
        left_right_compensation_min: float,
        left_right_compensation_max: float,
        left_right_compensation_offset: float,
    ) -> None:
        return self.dashboard.arc_track_params(
            sample_time,
            coordinate_type,
            up_down_compensation_min,
            up_down_compensation_max,
            up_down_compensation_offset,
            left_right_compensation_min,
            left_right_compensation_max,
            left_right_compensation_offset,
        )

    def arc_track_end(self) -> None:
        return self.dashboard.arc_track_end()

    def set_arc_track_offset(
        self,
        offset_x: float,
        offset_y: float,
        offset_z: float,
        offset_rx: float,
        offset_ry: float,
        offset_rz: float,
    ) -> None:
        return self.dashboard.set_arc_track_offset(
            offset_x, offset_y, offset_z, offset_rx, offset_ry, offset_rz
        )

    def rel_point_weld_line(
        self,
        start_x: float,
        end_x: float,
        y: float,
        z: float,
        work_angle: float,
        travel_angle: float,
        p1: collections.abc.Sequence[float],
        p2: collections.abc.Sequence[float],
    ) -> int:
        return self.dashboard.rel_point_weld_line(
            start_x, end_x, y, z, work_angle, travel_angle, p1, p2
        )

    def rel_point_weld_arc(
        self,
        start_x: float,
        end_x: float,
        y: float,
        z: float,
        work_angle: float,
        travel_angle: float,
        p1: collections.abc.Sequence[float],
        p2: collections.abc.Sequence[float],
        p3: collections.abc.Sequence[float],
    ) -> int:
        return self.dashboard.rel_point_weld_arc(
            start_x, end_x, y, z, work_angle, travel_angle, p1, p2, p3
        )

    def weave_start(self) -> None:
        return self.dashboard.weave_start()

    def weave_params(
        self,
        weld_type: int,
        frequency: float,
        left_amplitude: float,
        right_amplitude: float,
        direction: int,
        stop_mode: int,
        stop_time1: int,
        stop_time2: int,
        stop_time3: int,
        stop_time4: int,
        radius: float,
        radian: float,
        **kwargs,
    ) -> None:
        return self.dashboard.weave_params(
            weld_type,
            frequency,
            left_amplitude,
            right_amplitude,
            direction,
            stop_mode,
            stop_time1,
            stop_time2,
            stop_time3,
            stop_time4,
            radius,
            radian,
            **kwargs,
        )

    def weave_end(self) -> None:
        return self.dashboard.weave_end()

    def weld_arc_speed_start(self) -> None:
        return self.dashboard.weld_arc_speed_start()

    def weld_arc_speed(self, speed: float) -> None:
        return self.dashboard.weld_arc_speed(speed)

    def weld_arc_speed_end(self) -> None:
        return self.dashboard.weld_arc_speed_end()

    def weld_weave_start(
        self,
        weld_type: int,
        frequency: float,
        left_amplitude: float,
        right_amplitude: float,
        direction: int,
        stop_mode: int,
        stop_time1: int,
        stop_time2: int,
        stop_time3: int,
        stop_time4: int,
        radius: float,
        radian: float,
    ) -> None:
        return self.dashboard.weld_weave_start(
            weld_type,
            frequency,
            left_amplitude,
            right_amplitude,
            direction,
            stop_mode,
            stop_time1,
            stop_time2,
            stop_time3,
            stop_time4,
            radius,
            radian,
        )

    # --- Check ---

    def check_mov_c(
        self,
        j1a: float,
        j2a: float,
        j3a: float,
        j4a: float,
        j5a: float,
        j6a: float,
        j1b: float,
        j2b: float,
        j3b: float,
        j4b: float,
        j5b: float,
        j6b: float,
        j1c: float,
        j2c: float,
        j3c: float,
        j4c: float,
        j5c: float,
        j6c: float,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
    ) -> None:
        return self.dashboard.check_mov_c(
            j1a,
            j2a,
            j3a,
            j4a,
            j5a,
            j6a,
            j1b,
            j2b,
            j3b,
            j4b,
            j5b,
            j6b,
            j1c,
            j2c,
            j3c,
            j4c,
            j5c,
            j6c,
            user,
            tool,
            a,
            v,
            cp,
        )

    def check_mov_j(
        self,
        j1a: float,
        j2a: float,
        j3a: float,
        j4a: float,
        j5a: float,
        j6a: float,
        j1b: float,
        j2b: float,
        j3b: float,
        j4b: float,
        j5b: float,
        j6b: float,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
    ) -> None:
        return self.dashboard.check_mov_j(
            j1a,
            j2a,
            j3a,
            j4a,
            j5a,
            j6a,
            j1b,
            j2b,
            j3b,
            j4b,
            j5b,
            j6b,
            user,
            tool,
            a,
            v,
            cp,
        )

    def check_mov_l(
        self,
        j1a: float,
        j2a: float,
        j3a: float,
        j4a: float,
        j5a: float,
        j6a: float,
        j1b: float,
        j2b: float,
        j3b: float,
        j4b: float,
        j5b: float,
        j6b: float,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
    ) -> None:
        return self.dashboard.check_mov_l(
            j1a,
            j2a,
            j3a,
            j4a,
            j5a,
            j6a,
            j1b,
            j2b,
            j3b,
            j4b,
            j5b,
            j6b,
            user,
            tool,
            a,
            v,
            cp,
        )

    def check_odd_mov_c(
        self,
        j1a: float,
        j2a: float,
        j3a: float,
        j4a: float,
        j5a: float,
        j6a: float,
        j1b: float,
        j2b: float,
        j3b: float,
        j4b: float,
        j5b: float,
        j6b: float,
        j1c: float,
        j2c: float,
        j3c: float,
        j4c: float,
        j5c: float,
        j6c: float,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
    ) -> None:
        return self.dashboard.check_odd_mov_c(
            j1a,
            j2a,
            j3a,
            j4a,
            j5a,
            j6a,
            j1b,
            j2b,
            j3b,
            j4b,
            j5b,
            j6b,
            j1c,
            j2c,
            j3c,
            j4c,
            j5c,
            j6c,
            user,
            tool,
            a,
            v,
            cp,
        )

    def check_odd_mov_j(
        self,
        j1a: float,
        j2a: float,
        j3a: float,
        j4a: float,
        j5a: float,
        j6a: float,
        j1b: float,
        j2b: float,
        j3b: float,
        j4b: float,
        j5b: float,
        j6b: float,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
    ) -> None:
        return self.dashboard.check_odd_mov_j(
            j1a,
            j2a,
            j3a,
            j4a,
            j5a,
            j6a,
            j1b,
            j2b,
            j3b,
            j4b,
            j5b,
            j6b,
            user,
            tool,
            a,
            v,
            cp,
        )

    def check_odd_mov_l(
        self,
        j1a: float,
        j2a: float,
        j3a: float,
        j4a: float,
        j5a: float,
        j6a: float,
        j1b: float,
        j2b: float,
        j3b: float,
        j4b: float,
        j5b: float,
        j6b: float,
        user: int = -1,
        tool: int = -1,
        a: int = -1,
        v: int = -1,
        cp: int = -1,
    ) -> None:
        return self.dashboard.check_odd_mov_l(
            j1a,
            j2a,
            j3a,
            j4a,
            j5a,
            j6a,
            j1b,
            j2b,
            j3b,
            j4b,
            j5b,
            j6b,
            user,
            tool,
            a,
            v,
            cp,
        )

    # --- END GENERATED FORWARDS ---

    # ==================================================================
    # Lazy feedback properties
    # ==================================================================

    @property
    def feedback(self) -> DobotApiFeedback:
        """Feedback connection on port 30004 (8 ms cycle)."""
        if self._feedback is None:
            self._feedback = DobotApiFeedback(self.ip, 30004)
        return self._feedback

    @property
    def feedback_30005(self) -> DobotApiFeedback:
        """Feedback connection on port 30005 (200 ms cycle)."""
        if self._feedback_30005 is None:
            self._feedback_30005 = DobotApiFeedback(self.ip, 30005)
        return self._feedback_30005

    @property
    def feedback_30006(self) -> DobotApiFeedback:
        """Feedback connection on port 30006 (configurable cycle)."""
        if self._feedback_30006 is None:
            self._feedback_30006 = DobotApiFeedback(self.ip, 30006)
        return self._feedback_30006

    # ==================================================================
    # Lifecycle
    # ==================================================================

    def close(self) -> None:
        """Close all open connections."""
        self.dashboard.close()
        if self._feedback is not None:
            self._feedback.close()
        if self._feedback_30005 is not None:
            self._feedback_30005.close()
        if self._feedback_30006 is not None:
            self._feedback_30006.close()

    def reconnect(self) -> None:
        """Reconnect the dashboard and any active feedback connections."""
        self.dashboard.reconnect()
        if self._feedback is not None:
            self._feedback.reconnect()
        if self._feedback_30005 is not None:
            self._feedback_30005.reconnect()
        if self._feedback_30006 is not None:
            self._feedback_30006.reconnect()

    def __enter__(self) -> "DobotRobot":
        return self

    def __exit__(self, *exc_info) -> None:  # type: ignore[override]
        self.close()

    # ==================================================================
    # Error convenience (composes dashboard + error monitor)
    # ==================================================================

    def check_errors(self, language: Optional[str] = None) -> bool:
        """Check and display current robot errors.

        Args:
            language: Override default language for error messages.

        Returns:
            ``True`` if errors are present, ``False`` otherwise.
        """
        lang = language or self._language
        return self.errors.check_errors(lang)

    def clear_robot_error(self, language: Optional[str] = None) -> bool:
        """Clear robot errors and verify they are gone.

        Args:
            language: Override default language for error messages.

        Returns:
            ``True`` if errors remain after clearing, ``False`` if clear.
        """
        self.dashboard.clear_error()
        lang = language or self._language
        return self.errors.check_errors(lang)

    # ==================================================================
    # Feedback convenience (composes lazy feedback)
    # ==================================================================

    def feedback_data(self) -> Optional[FeedbackData]:
        """Get feedback data as a typed dataclass (port 30004).

        Returns:
            ``FeedbackData`` instance, or ``None`` if no valid data.
        """
        return self.feedback.feedback_data()

    def raw_feedback_data(self) -> Optional[np.ndarray]:
        """Get raw feedback data as numpy array (port 30004).

        Returns:
            Numpy structured array, or ``None`` if no valid data.
        """
        return self.feedback.raw_feedback_data()
